### ISSUE TITLE
System install

### ISSUE THREAD

**Issue by pablrod** [pablrod/p5-Alien-XGBoost#1]
I'm not able to make a working system install. 
When I return 'system' from probe phase then the installed `Alien::XGBoost` module has `dynamic_libs` empty.  
I've tried with this gather phase:
```perl
probe sub {
   ($library) = FFI::CheckLib::find_lib_or_die(lib => 'xgboost',
       verify => sub {
            my($name, $libpath) = @_;
            my $platypus = FFI::Platypus->new;
            $platypus->lib($libpath);
            # This function was defined recently
            my $f = $platypus->function('XGDMatrixCreateFromMat_omp', [] => 'int'); 
        }
    );
    return (defined $library ? 'system' : 'share');
};

sys {
    gather sub {
         my ($build) = @_;
         $build->runtime_prop->{dynamic} = $library
    };
};
```

**Comment by plicease** [comment]
I don't have a system xgboost to  test this, but you should be able to do this by setting ffi_name in the `sys` block:

```perl
sys {
  gather sub {
    my($build) = @_;
    $build->runtime_prop->{ffi_name} = 'xgboost';
  };
};
```

`Alien::Base` will do a find_lib at run-time to get the up-to-date location of the appropriate .so or .dll.

As an aside: I am curious why you chose to use `Alien::Build::MB` over `Alien::Build::MM`.

**Comment by pablrod** [comment]
Thanks for your comments!!
I've overlooked the runtime property `ffi_name`! But after adding it, the call `Alien::XGBoost->dynamic_libs` returns `undef`. I've tracked down this to line 318 of `Alien::Base`
```perl
    my $name = $class->config('ffi_name');
``` 
And after that the line 273, method `config`
```
    return $ab_config->{legacy}->{$key};
```
This is because the `ffi_name` property is defined out of the legacy hash. The fallback to using the `name` property also fails because I didn't set a `name` property.
These are the contents of `$ab_config`:
```perl
{  'ffi_name'            => 'xgboost',
   'alien_build_version' => '1.02',
   'prefix' => '/usr/local/lib64/perl5/auto/share/dist/Alien-XGBoost',
   'perl_module_version' => '0.01',
   'install_type'        => 'system',
   'legacy'              => {
				 'original_prefix' =>
				   '/usr/local/lib64/perl5/auto/share/dist/Alien-XGBoost',
				 'finished_installing' => 1,
				 'version'             => undef,
				 'install_type'        => 'system'
   },
   'distdir' => '/usr/local/lib64/perl5/auto/share/dist/Alien-XGBoost'
};
```
If I set the property as this, it works.
```
sys {
    gather sub {
       my ($build) = @_;
       $build->runtime_prop->{legacy}{ffi_name} = 'xgboost';
    };
};
```
But this leave me a feeling that I'm doing something wrong...

I'm using `Module::Build` after reading Effective Perl Programming 2nd Edition. Chapter 9, item 79. This item convinced me, I like the part that the build scripts are Perl scripts. And because this, I'm using 'Module::Build' in all of my modules. But the book was written in 2010...
After reading this: [Integrating with Module::Build](https://metacpan.org/pod/distribution/Alien-Build/lib/Alien/Build/Manual/AlienAuthor.pod#Integrating-with-Module::Build) I started to question the choice, but I don't know why.
In this case, thanks to your work is very easy to change between them, so if it's easier to maintain using `Alien::Build::MM` or another reason I'm very open to change, even all of my modules.

**Comment by plicease** [comment]
Indeed, as I looked closer at this `ffi_name` seems to be unimplemented using the new system.  It works with the PkgConfig plugin, but since you aren't using it there wasn't an interface for it.  Can you please give 1.03_02 a try for me?

https://metacpan.org/release/PLICEASE/Alien-Build-1.03_02

I have a unit test for the feature now, but it would be nice to know that it works with a real alien.

As for `Module::Build`, I used to use it almost exclusively for Aliens because the ability to subclass makes writing Aliens much easier.  Since 2010 it has fallen out of favor with the toolchain folks who maintain both MB and EUMM.  It has even been removed from the core.  Part of the rationale for the `Alien::Build` project was to support EUMM, which is bundled with Perl.  (Or really more to the point any installer, as you alluded to in your comment).  I think the main disadvantage of Alien::Build::MB is that it adds two extra non-core dependencies you might not otherwise need: Alien-Build-MB and Module-Build.  I think MB will be around for a while at any rate, so use whatever you want, but maybe just keep all of this in mind!

**Comment by pablrod** [comment]
Yeaah!! With 1.03_02 works perfectly!! Thanks!!

Ok! After knowing that, I'm going to use EUMM over MB progressively. For this alien, as soon as I make a new release.

Thank you again!!

**Comment by pablrod** [comment]
Closed via ba447fe0ed01cb2d4a38becdc7a46c691cd2621c

**Comment by plicease** [comment]
You should add 1.03 as a prereq since it has a fix you need for ffi_name.

**Comment by pablrod** [comment]
Oh! Yes! Thanks! As 1.03_01 and 1.03_02 are developer releases, I've added 1.04 as a prereq
